# Generated by Django 4.0.4 on 2022-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=90)),
                ('slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(upload_to='blog/images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
            ],
            options={
                'ordering': ('-published_on',),
            },
        ),
    ]
