# Generated by Django 4.0.4 on 2022-05-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='slug_field',
        ),
    ]
