# Generated by Django 4.0.4 on 2022-05-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_slug_blogpost_slug_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
